# Generated by Django 2.0.2 on 2018-03-21 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whichsandwich', '0002_sandwich_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
