# Generated by Django 2.0.2 on 2018-03-23 02:05

from django.db import migrations, models
import whichsandwich.models


class Migration(migrations.Migration):

    dependencies = [
        ('whichsandwich', '0003_auto_20180321_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='image',
            field=models.ImageField(blank=True, upload_to=whichsandwich.models.user_directory_path),
        ),
    ]
