# Generated by Django 2.0.2 on 2018-03-27 22:33

from django.db import migrations
import imagekit.models.fields
import whichsandwich.models


class Migration(migrations.Migration):

    dependencies = [
        ('whichsandwich', '0004_auto_20180323_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=whichsandwich.models.user_directory_path),
        ),
    ]
